canonical/postgresql-operator

- .github/workflows/ci.yaml
In short this PR address JIRA ticket [DPE-135](https://warthogs.atlassian.net/browse/DPE-135).
In long:
* The current CI configuration of this repository is triggering the actions execution whenever someone pushes some code to it.
* Fix the CI trigger to execute only when pushing to main (which is expected to happen only when merging a pull request) and when creating a pull request.
* There was the same issue in the [k8s operator repository](https://github.com/canonical/postgresql-k8s-operator/pull/5).
* Update CI to trigger only when creating a pull request and when pushing to main.
> DPE-135 Update CI trigger

- charmcraft.yaml
- metadata.yaml
- src/charm.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
- tox.ini
In short this PR partially address JIRA ticket [DPE-71](https://warthogs.atlassian.net/browse/DPE-71). The remaining implementation is split in two separate PRs to make the review easier.
In long:
* In order to enable automatic failover and replication through Patroni in a PostgreSQL deployment we need to change the way PostgreSQL is bootstraped/started (Patroni should be started; it'll start PostgreSQL later).
* Patroni is released as a Python package, which should be installed by the charm to later be started.
* Enable the human operator to inform a resource containing Patroni Python package when deploying.
* Installing this resource together with PostgreSQL database in the charm
* Additional Patroni dependencies (like python-dev and psycopg2) will be changed to be installed as offline …
> DPE 71 Patroni resource install

- .gitignore
- metadata.yaml
- src/charm.py
- src/cluster.py
- tests/helpers.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
In short this PR partially address JIRA ticket [DPE-71](https://warthogs.atlassian.net/browse/DPE-71). The remaining implementation is split in three separate PRs to make the review easier.
In long:
* In order to enable automatic failover and replication through Patroni in a PostgreSQL deployment we need to change the way PostgreSQL is bootstraped/started (Patroni should be started; it'll start PostgreSQL later).
* For this specific PR we need to provide some additional functions to create configuration files for Patroni and also to start it later.
* Generate configuration file (patroni.yml) and systemd unit file (patroni.service).
* Add helper functions to get unit IP, change owner of file and create directory.
* Add replication password.
* Add function to start Patroni.
A call to …
> DPE-71 - Add Patroni functions

- actions.yaml
- pyproject.toml
- requirements.txt
- src/charm.py
- src/cluster.py
- templates/patroni.yml.j2
- tox.ini
This is a PR that was on hold to copy the feedback that improved the PR from https://github.com/canonical/postgresql-k8s-operator/pull/9.
It is part of the scale up/down logic that is needed to avoid adding or removing more than one member to a PostgreSQL cluster if another member is still syncing data after it has joined.
In long:
* To avoid overload of the network during copy of data between the replicas that are being added to the cluster during a scale up or downtime in the case of a scale down, the charm needs to add and remove on member at a time from the cluster so.
* If the member is the current primary, we need to trigger a switchover before the unit is removed, to make avoid downtime in the cluster.
* Add some helper methods to add/remove one member at a time and also trigger a …
> Scaling helper methods

- tests/unit/test_postgresql_provider.py
ops 1.5.2 introduced a fix to the harness' handling for departing unit tracking for events.  This uncovered a subtle error in the tests here. remove_relation was triggering the "departing" relation data key to be inserted into the local charm's data because the local charm had been added to the relation units list (which is not really how that is intended to be used).  This was causing the delete_user method to be called earlier than intended and caused assertion failures in the on_relation_broken test.  The fix is to not add the local unit to the relation units.  But then the relation departed test that checks for the "departing" data key wasn't working.  So for now, we can add the local unit to the relation in that test only.
> fix departing unit subtleties

- pyproject.toml
- src/charm.py
- src/relations/db.py
- src/relations/postgresql_provider.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_db.py
- tests/unit/test_postgresql_provider.py
- tox.ini
* [DPE-1073](https://warthogs.atlassian.net/browse/DPE-1073)
* Low log verbosity when deferring events within the charm
* [DPE-1080](https://warthogs.atlassian.net/browse/DPE-1080)
* Warnings in unit tests
* Add debug log messages on event deferrals and early returns
* Clear up warnings
* Added log messages within the charm, didn't touch or check library code deferrals
* Added a patch to a unit test that fails if dpkg is not present on the system
* Switch to tox ini to use `allowlist_externals`
* Enabled SIMULATE_CAN_CONNECT for relevant tests
* Adding unit test dependency to suppress the  asyncio_mode warning config
* Increased a bit the unit test coverage
Increased log verbosity on deferrals
[DPE-1073]: https://warthogs.atlassian.net/browse/DPE-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> DPE 1073 DPE 1080: DEBUG verbosity for deferrals and early returns

- .github/workflows/release.yaml
- tox.ini
As the `ubuntu-latest` GH runner image was updated to jammy, the step that publishes the charm will break (due to using `--destructive-mode`).
We can see the issue on the [last attempt to publish the charm](https://github.com/canonical/postgresql-operator/actions/runs/3848767990/jobs/6560271111#step:4:13).
Pin focal runner image (`ubuntu-20.04`) on release workflow.
Jammy was not added to `charmcraft.yaml` because it will require some adjustments on the tests (and maybe also in the charm code).
Tested `sudo charmcraft pack --destructive-mode --quiet` manually on a focal VM.
Pin focal runner image on release workflow.
> Pin OS on release workflow

- .github/workflows/release.yaml
- lib/charms/postgresql_k8s/v0/postgresql.py
- tests/integration/new_relations/application-charm/metadata.yaml
- tests/integration/new_relations/application-charm/src/charm.py
- tests/integration/new_relations/test_new_relations.py
- tox.ini
Jira issue: [DPE-991](https://warthogs.atlassian.net/browse/DPE-991)
Also fixes: [DPE-1066](https://warthogs.atlassian.net/browse/DPE-1066)
When a charm relates to the database interface without providing a database name and later the relation is removed the PostgreSQL charm tries to delete the database user that was not created (because the database user is only created if the relation is complete: the other application needs to provide a database name for that).
Check whether the database user exists before the charm tries to delete it by importing the updated `lib/charms/postgresql_k8s/v0/postgresql.py` library from https://github.com/canonical/postgresql-k8s-operator/pull/75.
In summary, this is a copy and paste of the PR from the k8s charm. …
> Fix delete user call when user was not created before

- lib/charms/postgresql_k8s/v0/postgresql_tls.py
- requirements.txt
- tests/integration/test_db.py
- tox.ini
* [DPE-1081](https://warthogs.atlassian.net/browse/DPE-1081)
* Old lib juju is causing warnings in integration tests execution
* update to latest version of libjuju for 2 (2.9.38.1)
* Only one test seemed to break
* Also updating flake8 to the latest version expected to work
* Also updating ops requirement to latest stable (1.5.4)
[DPE-1049]: https://warthogs.atlassian.net/browse/DPE-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1081]: https://warthogs.atlassian.net/browse/DPE-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating libjuju to latest version for 2

- src/relations/db.py
- tests/integration/test_db.py
- tests/unit/test_db.py
- tox.ini
* [DPE-1049](https://warthogs.atlassian.net/browse/DPE-1049)
* Relating fails if  `event.app` is None
* More resilient check for database name and extensions 
* The VM charm is also affected by perpetual blocked status if extensions are requested, so the check to unblock is also copied
* Adds integration test for relating with weebl
* Adds unit tests for extension unblocking logic
* More resilient check for database name and extensions
* Unblock charm when relations requesting extensions are broken
[DPE-1049]: https://warthogs.atlassian.net/browse/DPE-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Legacy interface fails to relate if event attributes are None

- lib/charms/postgresql_k8s/v0/postgresql_tls.py
- src/relations/db.py
- tests/unit/test_db.py
* [PR#53](https://github.com/canonical/postgresql-operator/pull/53) silently broke the unit tests due to running CI on older ops version (1.5.4)
* Fix issues resulting from the ops update
* One of the unit tests added in [PR#53](https://github.com/canonical/postgresql-operator/pull/53) doesn't seem to be possible anymore with the test harnesss relation broken functionality. It may be possible to reproduce it using mock events and calling the `_on_relation_broken()` directly
* Also updating postgres_tls
> Fix unit tests

- tests/integration/ha_tests/conftest.py
- tests/unit/test_charm.py
Jira ticket: [DPE-1190](https://warthogs.atlassian.net/browse/DPE-1190)
The fixture called `wal_settings` was failing if another error happened stopping the SST test.
Start the stopped units (they were stopped inside the SST test). This makes the Patroni REST API available again to enable the fixture to rollback the changes in the WAL settings (that were made in the beginning of the test by this fixture) on all the units.
Still need to address transient errors (that triggered the error fixed by this PR in the past) in another PR.
Manually tested locally.
Fix change WAL settings fixture to start the stopped units.
[DPE-1190]: https://warthogs.atlassian.net/browse/DPE-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix change WAL settings fixture

- lib/charms/data_platform_libs/v0/database_provides.py
- lib/charms/operator_libs_linux/v0/apt.py
- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- requirements.txt
- tests/unit/test_charm.py
- tox.ini
* [DPE-1158](https://warthogs.atlassian.net/browse/DPE-1158)
* Update ops framework to latest stable
* Update ops
* Update charm libs to latest
* Update ops framework
[DPE-1158]: https://warthogs.atlassian.net/browse/DPE-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ops and charm libs version bump

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- CONTRIBUTING.md
- charmcraft.yaml
- metadata.yaml
- tests/integration/ha_tests/application-charm/charmcraft.yaml
- tests/integration/ha_tests/conftest.py
- tests/integration/ha_tests/test_self_healing.py
- tests/integration/helpers.py
- tests/integration/new_relations/application-charm/charmcraft.yaml
- tests/integration/new_relations/test_new_relations.py
- tests/integration/test_charm.py
- tests/integration/test_db.py
- tests/integration/test_db_admin.py
- tests/integration/test_password_rotation.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
Jira issue: https://warthogs.atlassian.net/browse/DPE-1413
The charm is still on Focal.
Upgrade all the bases and all the deployments to use Jammy.
The Landscape bundle test was disabled due to incompatibilities. Ticket to manage those incompatibilities: https://warthogs.atlassian.net/browse/DPE-1414
A lot of changes in the tests related to the database app name constant are due to removing multiple series in the tests.
Used the existing tests to confirm that the charm works on Jammy.
Upgrade charm to Jammy.
> Upgrade to jammy

- .github/workflows/ci.yaml
Jira tickets: [DPE-1419](https://warthogs.atlassian.net/browse/DPE-1419)
The integration tests are not running in the latest Juju agent version due to a bootstrap constraint (`--agent-version=2.9.34`)
Update the Juju agent version in the bootstrap constraint from `.github/workflows/ci.yaml`.
Juju Python library was updated to fix https://bugs.launchpad.net/juju/+bug/1992833 (and it's already updated in this repo).
Executed the existing tests and all of them worked fine.
Bump juju from 2.9.34 to 2.9.38 (latest)
[DPE-1419]: https://warthogs.atlassian.net/browse/DPE-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump juju from 2.9.34 to 2.9.38 (latest)

- .github/workflows/ci.yaml
- actions.yaml
- src/backups.py
- src/charm.py
- src/cluster.py
- src/constants.py
- templates/patroni.yml.j2
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/test_backups.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tox.ini
Jira ticket: [DPE-1192](https://warthogs.atlassian.net/browse/DPE-1192)
Backup cannot be restored in the charm.
Add an action to perform the restore of a backup in the unit.
This PR is mostly a copy and paste of https://github.com/canonical/postgresql-k8s-operator/pull/104 (here the calls to pgBackRest to use subprocess instead of pebble).
Also, the other difference is that the removal of previous cluster information is done after the database is started again, because `patronictl remove` (the command used for that) cannot be executed while Patroni is down and it cannot be executed before stopping the database (because Patroni will keep the cluster info).
Summary of the changes:
* `actions.yaml`: added the restore action.
* `src/backups.py`: added the event handler for the action with the …
> pgBackRest restore action

- src/relations/postgresql_provider.py
- tests/unit/test_postgresql_provider.py
Just adding the database field in the provider side. This is to follow the interface signature change https://github.com/canonical/charm-relation-interfaces/pull/43
> [MISC] Add database field in the provider-side databag

- src/charm.py
- src/cluster.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
Jira ticket: [DPE-1415](https://warthogs.atlassian.net/browse/DPE-1415)
When deploying a 3+ unit cluster, often one of the units gets stuck in a `awaiting for member to start` Waiting status.
This happened because TCP connections between the 3rd+ replica to the primary were being aborted after being created (couldn't figure out the reason yet).
When the 3rd+ member is added to the cluster, first of all add it to the raft cluster, so it can communicate with the primary and participate in the primary election later (and also be in sync with the cluster).
* In `src/charm.py`:
* Added a call to restart Patroni and enable the node to correctly connect to the cluster.
* In `src/cluster.py`
* Added a property that returns whether the member is isolated from the cluster (what happens in the …
> Restart the service when the member is isolated from the rest of the cluster

- src/charm.py
- src/constants.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
* [DPE-1647](https://warthogs.atlassian.net/browse/DPE-1647)
* Pin the charmed postgresql snap
Hold charmed-postgresql snap to revision 31
[DPE-1647]: https://warthogs.atlassian.net/browse/DPE-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hold the postgresql snap to a specific revision

- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_self_healing.py
Jira ticket: [DPE-541](https://warthogs.atlassian.net/browse/DPE-541)
PostgreSQL should self heal after cutting the network connection and reestablishing it (when the network cut doesn't cause a change in the unit IP address).
Limit the network connection of the unit to 0 kbit of egress traffic and 1 kbit of ingress traffic (the minimum allowed), and by reducing the priority of the traffic sent to the unit to the lowest.
In `tests/integration/ha_tests/helpers.py`:
* Added the helper functions needed to perform the network cut/restore operations (they don't cause an unit IP change).
In `tests/integration/ha_tests/test_self_healing.py`:
* Added the network cut test (the one where the unit IP doesn't change).
[DPE-541]: https://warthogs.atlassian.net/browse/DPE-541?atlOrigin=eyJpIjoiNWRkNTljN …
> Add network cut test (without unit IP change)

- src/constants.py
* Update the charm to latest published snap, that removes superfluous dependencies
Remove unneeded dependencies in the charmed-postgresql snap
> Remove unneeded dependenceis from charmed-postgresql snap

- lib/charms/data_platform_libs/v0/data_interfaces.py
- src/constants.py
- tests/integration/helpers.py
Security scan detected outdated packages in the charmed-postgresql snap:
```
Revision r50 (amd64; channels: 14/edge)
* libpq5: 6104-1
* postgresql-14: 6104-1
* postgresql-client-14: 6104-1
* postgresql-plpython3-14: 6104-1
```
* Rebuild the snap and updated the held revision
* Updated charm libs
* Increased switchover timeout
> Refresh snap due to packages update

- src/backups.py
- tests/integration/conftest.py
- tests/unit/test_backups.py
- tests/unit/test_charm.py
The backup and restore features don't have unit tests.
Add unit tests for 1/3 of the implemented methods.
The remaining 2/3 of unit tests were implemented on https://github.com/canonical/postgresql-operator/pull/146 and https://github.com/canonical/postgresql-operator/pull/148 to keep this PR small.
Part of the `_on_create_backup_action` was extracted to another method to avoid a too complex method (warned by the lint job).
Some other adjustments were made:
* An unnecessary block of code was removed from `src/backups.py`.
* Added a check to turn off the connectivity to the database only when it's a replica (it's what is being done in the k8s charm and was missed in this charm).
> [DPE-557] Add 2nd batch of backup/restore unit tests

- src/backups.py
- tests/unit/test_backups.py
The backup and restore features don't have unit tests.
Add unit tests for 1/3 of the implemented methods.
The remaining 2/3 of unit tests were implemented on https://github.com/canonical/postgresql-operator/pull/146 and https://github.com/canonical/postgresql-operator/pull/149 to keep this PR small.
The logic that fixes slashes in the S3 path was moved in `src/backups.py` to handle that in the right place (after a default path is set).
> [DPE-557] Add 3rd batch of backup/restore unit tests

- src/backups.py
- src/charm.py
We are not logging the success or failure of both the `create-backup` and `restore` actions in a way that is easy for other applications to parse the logs related to success or failure on those operations.
Copied from https://github.com/canonical/postgresql-k8s-operator/pull/181.
Log failures (as errors) and successes (as info) to the debug log. The failures have prefix `Backup failed`/`Restore failed`, the successes have prefix `Backup successful`/`Restore successful`.
The `Restore successful` message can be logged only after Patroni starts (which happens some time after the execution of the `restore` action).
> [DPE-1915] Backup and restore log messages

- tests/integration/test_db.py
The new Nextcloud charm revision (released on June 15th) is failing as on https://pastebin.canonical.com/p/PCVKx49j7R/, even when it's the only charm that is deployed in the model (no PostgreSQL to relate to it). This is blocking releases on the main branch of this repository.
Reference: https://github.com/erik78se/nextcloud-charms/issues/61#issuecomment-1593605323
Mark the test as unstable temporarily.
The test should be enabled back again (with improvements to check that the charm works when extensions are enabled) on [DPE-2130](https://warthogs.atlassian.net/browse/DPE-2130).
[DPE-2130]: https://warthogs.atlassian.net/browse/DPE-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DPE-2129] Mark failing Nextcloud test as unstable temporarily

- src/backups.py
- tests/unit/test_backups.py
The charm doesn't recovers automatically from a blocked state due to connection blocked by firewall rules after they are fixed neither allow the user to do some action to fix the blocked status.
Instead of setting a blocked status when any operation related to the stanza happens, raise an error, which enables the user to call `juju resolve` after the network issue is fixed.
This was changed in three different places in case the connection is blocked in specific protocols, allowing one operation but timing out in the next one.
Closes https://github.com/canonical/postgresql-operator/issues/129.
> [DPE-1712] Enabled the user to fix network issues and rerun stanza related hooks

- src/constants.py
Security scan report:
```
Revision r61 (amd64; channels: 14/edge)
* libc-ares2: 6164-1
```
Rebuild and update snap
> Update revision due to outdated packages

- .github/workflows/release.yaml
- tests/integration/test_db.py
Charm is published to charmhub on each push to main even if there are no changes to the charm itself
Try to limit the amount of releases based on the content of the push
> Internal changes to the charm shouldn't be released

- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/backups.py
- src/charm.py
- src/cluster.py
- src/constants.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
Users don't know that psql and patronictl are installed together with the snap
Adding aliases manually for the snapped application.
https://github.com/canonical/operator-libs-linux/pull/94 would allow us to do the same from the charm lib
Also updated charm libs
> [DPE-2090] Add aliases

- src/relations/db.py
- tests/integration/helpers.py
- tests/integration/test_db.py
- tests/integration/test_db_admin.py
- tests/unit/test_db.py
When relating more that one unit of the Landscape charm, one of its units became in a waiting state due to wrong data being sent by the PostgreSQL charm in the `allowed-units` relation data field.
Use spaces instead of commas as the separator in the `allowed-units` relation data field, as the legacy PostgreSQL charm does. The legacy PostgreSQL K8S charm uses commas (so we will keep the legacy relation from the new PostgreSQL K8S charm as it is right now). We should only change PgBouncer VM. I'm gonna create a PR for that.
Closes https://github.com/canonical/postgresql-operator/issues/171.
> [DPE-2173] Fix allowed units relation data field

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- tests/integration/new_relations/helpers.py
- tests/integration/new_relations/test_new_relations.py
Users created for the relations established have access to all the databases because when a new database is created, PostgreSQL enable all the users to connect to it by default.
Restrict access to the system database to the system users and to the newly created database only to the user that requested it.
> [DPE-2127] Fixed databases access

- .github/workflows/ci.yaml
- src/charm.py
- src/cluster_topology_observer.py
- tests/unit/test_charm.py
A bug was reported in the public MM that the legacy relation for VM doesn't fire the hook to update the primary. It seems to me that the topology observer has crashed at some point and changes in the topology are no longer passed on to relations.
Check that the observer is still alive in  _on_update_status and restart it if it os not. This is more of a POC fix to see if it will resolve the bug. If it is indeed the issue at hand, we can revisit with a better solution.
> [MISC]  More resilient topology observer

- tests/integration/ha_tests/test_self_healing.py
Disable the network cut tests until we can spend some time on stabilising them.
> [MISC] Disable network cut tests

- src/constants.py
Security notice:
```
Revision r68 (amd64; channels: 14/edge)
* libpq5: 6296-1
* postgresql-14: 6296-1
* postgresql-client-14: 6296-1
* postgresql-plpython3-14: 6296-1
```
> [MISC] Update snap due to outdated packages

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/relations/postgresql_provider.py
- tests/integration/new_relations/test_new_relations.py
When an application requests invalid extra user roles through the relation with the PostgreSQL charm, PostgreSQL become blocked and that status is not fixed even when removing the relation.
Check if there are still active relations with invalid extra user roles being requested and, if not, remove the blocked status (it's similar to what has been done for extensions in the legacy relations).
Added an additional integration test to validate that.
> [DPE-2236] Handle invalid extra user roles

- src/cluster.py
- templates/patroni.yml.j2
- tests/unit/test_cluster.py
Default configuration prevents socket connections for the operator user from within the charm machine
* Allow socket connections
* Restrict the access to Patroni configuration
> [DPE-2467] Socket connection

- .github/workflows/ci.yaml
- src/backups.py
- src/charm.py
- src/grafana_dashboards/postgresql-metrics.json
- tests/unit/test_backups.py
- tests/unit/test_charm.py
Starting the Postgresql exporter is frequently failing on replica units, likely due to LXD update.
Trigger the exporter start in on peer data change, after Patroni and PG are started.
> [MISC] Secondary units stuck on configuring exporter

- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/operator_libs_linux/v2/snap.py
- poetry.lock
- pyproject.toml
- requirements.txt
- src/backups.py
- src/charm.py
- tests/unit/test_backups.py
Copy of https://github.com/canonical/postgresql-k8s-operator/pull/240
Pgbackrest stanza check requires  TLS servers to run if enabled, but they won't start until the hook is released and peer data is updated.
Run only stanza create in the s3 relation hooks and trigger the stanza check via peer relation change
> [DPE-2614] Split stanza create and stanza check

- config.yaml
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/cluster.py
- templates/patroni.yml.j2
- tests/integration/ha_tests/test_replication.py
- tests/integration/ha_tests/test_restore_cluster.py
- tests/integration/ha_tests/test_self_healing.py
- tests/integration/test_db.py
- tests/integration/test_password_rotation.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
Profiles support missing from PG
Same as PG K8s [PR#245](https://github.com/canonical/postgresql-k8s-operator/pull/254)
> DPE-2617 Basic profile support

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- tests/unit/test_charm.py
Port of pg-k8s [pr#260](https://github.com/canonical/postgresql-k8s-operator/pull/260)
> DPE-2617 autotune production profile

- src/charm.py
Charm can fail on reconfiguring if the departing unit is already gone from the relation databag:
```
unit-postgresql-24: 13:06:29 DEBUG unit.postgresql/24.juju-log database-peers:42: Re-emitting deferred event <RelationChangedEvent via Postgres
qlOperatorCharm/on/database_peers_relation_changed[112]>.
unit-postgresql-24: 13:06:29 ERROR unit.postgresql/24.juju-log database-peers:42: Uncaught exception while in charm code:
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-postgresql-24/charm/./src/charm.py", line 1436, in <module>
main(PostgresqlOperatorCharm)
File "/var/lib/juju/agents/unit-postgresql-24/charm/venv/ops/main.py", line 439, in main
framework.reemit()
File "/var/lib/juju/agents/unit-postgresql-24/charm/venv/ops/framework.py", line 851, in reemit …
```
> [MISC] Don't fail if the unit is already missing

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/upgrade.py
- src/constants.py
- src/dependency.json
Bumps the snap with the changes from https://github.com/canonical/charmed-postgresql-snap/pull/23
> [DPE-2721] Allow network access for pg_dump, pg_dumpall and pg_restore

- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- renovate.json
- src/charm.py
- src/cluster_topology_observer.py
- src/grafana_dashboards/postgresql-metrics.json
- tests/unit/test_charm.py
- tests/unit/test_cluster_topology_observer.py
* Copy over dash changes from the K8s charm.
* Use the correct custom event dispatcher depending on the juju version
> [DPE-2717] Copy dashboard changes from K8s and use the correct topology dispatcher

- .github/workflows/cla-check.yml
Check if Canonical's Contributor License Agreement has been signed by the PR author(s).
> add CLA check

- .github/workflows/ci.yaml
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/db.py
- src/relations/postgresql_provider.py
- tests/unit/test_db.py
- tests/unit/test_postgresql_provider.py
Port of https://github.com/canonical/postgresql-k8s-operator/pull/290
> [DPE-2569] Extensions not enabled when database is created

- .github/workflows/ci.yaml
- .github/workflows/lib-check.yaml
- .github/workflows/release.yaml
Checking charm libs requires credentials that are not available to contributors outside of the DPE team.
Split the checking action in a separate workflow that is not run on forked PRs.
> [DPE-2804] Split off lib check

- tests/integration/new_relations/test_new_relations.py
- tests/integration/test_backups.py
- tests/integration/test_charm.py
- tests/integration/test_db_admin.py
- tests/integration/test_plugins.py
Setting testing profile in tests.
> [MISC] Missed profile sets

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/db.py
- tests/integration/test_plugins.py
- tests/unit/test_charm.py
- tests/unit/test_db.py
Starting a connection for each db to enable or disable plugins will take more and more time as the number of plugins increases.
Open a single connection per db and enable or disable the plugins in one go.
Copy of https://github.com/canonical/postgresql-k8s-operator/pull/322
> [DPE-2902] Toggle plugins in one go

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/grafana_agent/v0/cos_agent.py
- src/cluster.py
- src/constants.py
Updates from PPAs:
* Patroni 3.1.2
* Pgbackrest 2.48
> [DPE-3039] Update Snap

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/db.py
- src/relations/postgresql_provider.py
- tests/unit/test_charm.py
- tests/unit/test_db.py
- tests/unit/test_postgresql_provider.py
Some charms like Discourse-K8S need to have the ownership of the tables and other objects in a database to correctly run its migrations if a database from a previous Discourse installation is used, otherwise it will not complete the migrations and will throw an error. Also, the existing Discourse K8S test was marked as `unstable` in the past because that charm was migrated from the legacy to the modern relation interface.
This is a port of https://github.com/canonical/postgresql-k8s-operator/pull/334.
`lib/charms/postgresql_k8s/v0/postgresql.py` is copied from the K8S charm.
If the relation between PostgreSQL and Discourse K8S (or any other charm), continue with the same behaviour, but after another instance of the charm is related to the PostgreSQL again, requesting the same database, …
> [DPE-2740] Handle tables ownership

- lib/charms/data_platform_libs/v0/data_interfaces.py
- poetry.lock
- pyproject.toml
- src/charm.py
- tests/integration/test_db_admin.py
- tests/unit/test_charm.py
`data_platform_libs/data_interface v26`, together with additional tests.
The library now includes support for handling Peer Relation Data (similar to Cross-charm Relation Data), hiding all complexity of choice between databag and Juju Secrets.
The same code is also tested against Juju 3.1.7: https://github.com/canonical/postgresql-operator/pull/314
> Internal secrets management from library

- tests/unit/test_charm.py
With Juju secrets [only the leader unit has admin access to app secrets](https://discourse.charmhub.io/t/secret-access-permissions/12627), and ops 2.9 and above enforce this in `Harness` to match the Juju behaviour.
One test (`test_migration_from_single_secret`) currently does a `set_secret` call (via the charm's `set_secret method) when acting as a non-leader unit. This would not work in production, and fails in ops 2.9.
The PR simply calls `set_leader()` appropriately around the `set_secret` call, so that the rest of the test (in all three parameterised versions) remain unchanged.
> fix: secret tests must only set app secrets as the leader

- poetry.lock
- tests/integration/test_backups.py
- tests/integration/test_tls.py
Only a single TLS test uses the Self Signed Certificates operator on Juju 3.
Use the same approach implemented on [PgBouncer K8S](https://github.com/canonical/pgbouncer-k8s-operator/pull/191) (conditionally use TLS Certificates Operator or Self Signed Certificates operator, depending on the Juju version).
> [DPE-3422] Switch to self signed certificates

- .github/codecov.yml
- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/test_charm.py
- tox.ini
* Restore codecov and add configuration
> [MISC] Restore Codecov and update libs

- src/charm.py
- tests/integration/ha_tests/test_restore_cluster.py
- tests/unit/test_charm.py
The restore cluster test was failing a lot of times due to the `replication` user password not being updated, which led to follower units not being able to connect to the primary to get the data.
Update all users' passwords in the test.
Also, use this opportunity to change the blocked status with the message `no primary in the cluster` to a waiting status because it's resolved after some time (no need for user action).
> [DPE-3559] Stabilise restore cluster test

- lib/charms/postgresql_k8s/v0/postgresql.py
If we relate a charm like the MAAS operator to the PostgreSQL operator, remove the relation and relate again, then MAAS doesn't have access to the previously created PostgreSQL large objects.
https://github.com/canonical/postgresql-operator/issues/348
When a charm is related again to the PostgreSQL operator, give the ownership of the existing large objects to that charm user, as we already do for tables and other objects.
> [DPE-3544] Fix large objects ownership

- tests/integration/test_password_rotation.py
All this cases should be covered:
- Authentification should be enabled by default always. No anonymous/guest 
access ever;
- get-password and set-password functions should be created for internal 
users;
> Cover missing test cases for internal users

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_replication.py
- tests/integration/ha_tests/test_restore_cluster.py
- tests/integration/ha_tests/test_self_healing.py
- tests/integration/ha_tests/test_upgrade.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/new_relations/test_new_relations.py
- tests/integration/test_backups.py
- tests/integration/test_charm.py
- tests/integration/test_db.py
- tests/integration/test_db_admin.py
- tests/integration/test_password_rotation.py
- tests/integration/test_plugins.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
The validation for the `shared_buffers` parameter was not correct. The calculus of the maximum allowed shared buffers value was not correctly converting the available memory for that to the same unit as the `shared_buffers` parameter that the user informs.
Also, the `effective_cache_size` parameter did not consider the user-provided `shared_buffers` value.
One last issue: sometimes, the restart of the PostgreSQL database was not triggered because Patroni hadn't finished reloading the configuration (even after 10 seconds).
Fix the calculus of the maximum allowed shared buffers value to be in the same unit as the user-provided value.
Considered the user-provided shared buffers value for the effective cache size parameter calculus.
An improved retry mechanism was added to check whether a …
> [DPE-3591] Fix shared buffers validation

- README.md
Docs sync workflow is not yet added, so the badge doesn't render.
Removing the badge for now, to be added after `discourse-gatekeeper` integration.
> Removed doc sync workflow badge

- src/cluster.py
Try to catch the exception in https://github.com/canonical/postgresql-operator/issues/419
There are already handlers for RetryErrors, but we do not try to parse the json response within the tenacity attempt. There may be more underlying issues here, since patroni isn't responding with a valid json.
> [DPE-3895] Handle get patroni health exception

- tests/unit/test_charm.py
- tox.ini
Allow tests to run with `jujuVersion.has_secrets` both enabled and disabled. Move away from `unittest.TestCase`.
Tests are largely unaltered, with few exceptions:
- `test_delete_password` got removed and `test_delete_existing_password_secrets` now handles both versions with and without secrets.
- `test_update_certificate` got removed and `test_update_certificate_secrets` now handles both versions with and without secrets.
- `test_migration_from_databag` and `test_migration_from_single_secret` got adapted in order to run only if `has_secrets == True` since they test migration from databag to secrets.
Only two global pytest fixtures are used: `harness` and `_has_secrets`. Especific patches are kept inside their respective tests.
```
cd path/to/tests/
tox run -e unit
```
> [DPE-2674] Convert test_charm.py to pytest style testing instead of unittest

- .github/workflows/ci.yaml
- tests/integration/ha_tests/helpers.py
- tests/integration/test_subordinates.py
Port of https://github.com/canonical/pgbouncer-operator/pull/204
> [MISC] Switch to SaaS landscape

- tests/integration/helpers.py
- tests/integration/test_tls.py
Updated TLS test, added check for replicas encrypted connection
> Added check for replicas encrypted connection

- lib/charms/operator_libs_linux/v2/snap.py
After [this merged PR](https://github.com/canonical/operator-libs-linux/pull/119) we should update our lib version in order to use the new logging feature. 
`charmcraft fetch-lib charms.operator_libs_linux.v2.snap`
> [DPE-3845] Update operator_libs_linux library to version 2.5

- CONTRIBUTING.md
Issue:
The previous CONTRIBUTION guild didn't represent the latest code state and had missing mandatory dependencies installation.
Solution:
Update the guild providing the copy&paste manuals to:
* install all the necessary build dependencies
* document and avoid the possible pitfalls
> Update CONTRIBUTING.md to represent the recent build dependencies

- tests/unit/conftest.py
- tests/unit/test_backups.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_cluster_topology_observer.py
- tests/unit/test_db.py
- tests/unit/test_postgresql_provider.py
- tests/unit/test_upgrade.py
- tests/unit/test_utils.py
> [DPE-4068] Finish test migration from unittest to pytest + enable/disable secrets in every test

- src/charm.py
The charm should not restore the blocked status if the blocking condition is no longer valid
Related to https://github.com/canonical/postgresql-operator/issues/466
> [DPE-4336] Reset active status when removing extensions dependency block

- config.yaml
- src/charm.py
- src/config.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
Adds experimental support for force setting max_connections.
> [MISC] Add experimental max_connections config

- lib/charms/data_platform_libs/v0/s3.py
- src/backups.py
- templates/pgbackrest.conf.j2
- tests/unit/test_backups.py
Link to issue: https://warthogs.atlassian.net/browse/DPE-4401
Link to spec: https://docs.google.com/document/d/1WWMt_Q71cUIrpfYirp5TRCdkJXMjFSWCH6CTnKrO4YA/edit
The parameter `delete-older-than-days` (from s3-integrator) is used to set up retention time (in days) as a pgBackRest parameter, allowing for uses to configure a retention policy for their backups.
see K8s version https://github.com/canonical/postgresql-k8s-operator/pull/477
> [DPE-4401] Add retention time for full backups

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/rolling_ops/v0/rollingops.py
Issue:
It is impossible to upgrade charm from the current 14/stable to 14/candidate due to the issue https://warthogs.atlassian.net/browse/DPE-4416
Solution:
Fix dp-library in revision 36 https://github.com/canonical/data-platform-libs/pull/170
Update all libraries to the latest fixes/LIBPATCH.
Original issue is no longer reproducible and the new charm passed the internal testing.
> [DPE-4416] Fetch charm libs to the latest LIBPATCH (update dp-libs to v36 to fix secrets issue)

- src/backups.py
- tests/unit/test_backups.py
We cannot scale up if S3 and TLS relations are established. This operation leads to an error like the one below if, in the new unit, the S3 parameters relation changed event fires before the TLS files are available in the unit (and Patroni + PostgreSQL haven't started yet).
```sh
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.142.152.2', port=8008): Max retries exceeded with url: /cluster (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
```
Defer the S3 parameters relation changed event until that unit can do any operation related to S3 (or even connect to the other unit to check the cluster topology and verify it's not the primary unit so that it can …
> [DPE-4453] Fix scale up with S3 and TLS relations

- actions.yaml
- src/backups.py
- src/charm.py
- src/constants.py
- templates/pgbackrest.conf.j2
- tests/integration/test_backups.py
- tests/unit/test_backups.py
VM version of https://github.com/canonical/postgresql-k8s-operator/pull/476 and https://github.com/canonical/postgresql-k8s-operator/pull/487
https://warthogs.atlassian.net/browse/DPE-4475 for including incremental backup check in integration test.
> [DPE-4462] Add Incremental+Differential backup support

- .github/workflows/ci.yaml
Too high cost on GitHub-hosted ARM runners
Will try to re-enable on nightly only if costs are low enough, but disabling all for now so that new PR runs do not create further costs
> Disable ARM integration tests

- lib/charms/data_platform_libs/v0/upgrade.py
The PostgreSQL VM charm rollback test started to fail by the combination of adding TimescaleDB to the Charmed PostgreSQL Snap + updating the `upgrade` library to LIBPATCH 16 (which removed a `defer` call that was hiding the issue fixed by this PR).
Explanation of the issue (considering the tests from the PostgreSQL VM charm):
* In the `test_upgrade_from_edge` test:
* TimescaleDB in the snap is leading to a longer snap refresh (only some more seconds).
* With that, Patroni is performing a failover, so a new unit, different from the Juju leader unit (the former primary), becomes the primary.
* Also with that, the former primary unit, the Juju leader unit, becomes a replica (not a synchronous standby).
* In the `test_fail_and_rollback` test:
* After the failed upgrade, the …
> [DPE-4598] Handle upgrade of top of the stack Juju leader

- src/backups.py
- templates/pgbackrest.conf.j2
- tests/unit/test_backups.py
It's possible to configure a TLS CA chain in the S3 integrator charm. However, the PostgreSQL charm doesn't use that, so right now, it's not possible to connect to S3-compatible storages which provide a self-signed SSL certificate.
Port of https://github.com/canonical/postgresql-k8s-operator/pull/493.
Push the TLS CA chain contents to a file and reference it in the pgBackRest configuration (and also in the boto3 calls), so it uses that CA when communicating with the S3-compatible storage.
Manual testing:
1. Build and install the MicroCeph snap from the https://github.com/marceloneppel/microceph/tree/rgw-https-support branch.
```sh
snapcraft -v
sudo snap install --dangerous microceph_*.snap
```
2. Generate the SSL files.
```sh
sudo openssl genrsa -out /var/snap/microceph/common/ca.key 2048 …
```
> [DPE-4412] Use TLS CA chain for backups

- lib/charms/postgresql_k8s/v0/postgresql.py
- tests/integration/test_password_rotation.py
A port of https://github.com/canonical/postgresql-k8s-operator/pull/506
Integration test failing before the change: https://github.com/canonical/postgresql-operator/actions/runs/9505894254/job/26202369501?pr=495#step:21:430
Test passing afterwards: https://github.com/canonical/postgresql-operator/actions/runs/9506859106/job/26205708599?pr=495#step:21:264
> [DPE-4032] Exposed passwords on postgresql SQL queries logging

- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/postgresql_k8s/v0/postgresql_tls.py
- lib/charms/tempo_k8s/v1/charm_tracing.py
- lib/charms/tempo_k8s/v2/tracing.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
- tests/unit/test_cluster_topology_observer.py
- tests/unit/test_db.py
- tests/unit/test_postgresql_provider.py
- tests/unit/test_upgrade.py
- tests/unit/test_utils.py
* Bump charm libs
* Bump coverage above 70%
* Refactored some of the TestCase asserts to regular asserts
> [MISC] Increase coverage

- src/dependency.json
`_on_upgrade_charm_check_legacy()` logic is leading to a slow bootstrap of replicas.
This method is not needed anymore (only when upgrading from revision 288).
Bump the version in `src/dependency.json` so that after the next stable, we can bump the restrictions (`upgrade_supported` field) to allow the upgrade only from the latest stable (which will allow us to remove `_on_upgrade_charm_check_legacy()`).
> [DPE-4759] Bump version

- src/relations/postgresql_provider.py
- tests/unit/test_postgresql_provider.py
Port of https://github.com/canonical/postgresql-k8s-operator/pull/545
> [DPE-2278] Add libpq URI connection string to uri field in relation

- src/charm.py
Fix a missing case for peer to secrets translation.
> [MISC] Always check databag

- tests/integration/ha_tests/helpers.py
- tests/integration/test_tls.py
Try to reduce the TLS test flakyness.
> [DPE-4533] Pause Patroni in the TLS test

- pyproject.toml
Added in poetry 1.8
(metadata unused since charm is not a Python package)
> Use poetry package-mode=false

- tests/integration/ha_tests/test_async_replication.py
The `test_async_replication_failover_in_main_cluster` test often fails with the following error:
```sh
File "/home/runner/actions-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/test_async_replication.py", line 489, in test_async_replication_failover_in_main_cluster
assert new_sync_standby != sync_standby, "Sync-standby is the same as before"
AssertionError: Sync-standby is the same as before
assert 'postgresql-1' != 'postgresql-1'
```
Wait for the scale in operation to finish before checking whether the sync standby changed.
> [DPE-5029] Wait for exact number of units after scale down

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/tempo_k8s/v1/charm_tracing.py
- src/relations/db.py
- tests/unit/test_db.py
Conditionally update the db version field in legacy relations if database is not accessible.
Related to #352 and #566
> [DPE-3562] Don't block on failure to get the db version

- src/relations/postgresql_provider.py
- tests/unit/test_postgresql_provider.py
Move uri generation to `update_endpoints`
> [MISC] Move uri generation to update endpoints

- actions.yaml
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/tempo_k8s/v1/charm_tracing.py
- src/charm.py
- src/cluster.py
- src/cluster_topology_observer.py
- src/constants.py
- src/dependency.json
- src/relations/async_replication.py
- src/upgrade.py
- templates/patroni.yml.j2
- tests/integration/ha_tests/conftest.py
- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_self_healing.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/helpers.py
- tests/integration/test_backups.py
- tests/integration/test_charm.py
- tests/integration/test_db_admin.py
- tests/integration/test_password_rotation.py
- tests/integration/test_tls.py
- tests/unit/test_cluster.py
- tests/unit/test_upgrade.py
* Add passwords to Patroni and Syncobj
* Update libs
Closes https://github.com/canonical/postgresql-operator/issues/27
> [DPE-5269] Add passwords to Syncobj and Patroni

- src/cluster.py
- src/upgrade.py
- templates/patroni.yml.j2
- tests/unit/test_cluster.py
Conditionally add REST password to patroni config
> [MISC] Conditional password

- .github/workflows/lib-check.yaml
Check libs workflow also relied on the tox wrappers
> [MISC] Disable tox requirements generation for check libraries flow

- tests/integration/new_relations/test_new_relations.py
- tests/integration/test_backups.py
- tests/integration/test_backups_pitr.py
VM port of https://github.com/canonical/postgresql-k8s-operator/pull/707
>  [MISC] Use more meaningful group naming for multi-group tests

- src/charm.py
If the Posgresql and Pgbouncer charms are collocated on the same host, both will try to create a psql alias. The charm should ignore errors during alias creation, since the alias is not a critical component and collocation of both charms is a valid use case
Related to https://github.com/canonical/postgresql-operator/issues/636
> [DPE-5594] Ignore alias error in case alias is already existing

- config.yaml
- templates/patroni.yml.j2
Some of the `postgresql.conf` parameter values don't have the PM desired value for correctly hardening the charm.
Those are the following:
* log_connections
* log_disconnections
* log_error_verbosity
* log_min_error_statement
* debug_print_plan
* debug_print_parse
* debug_print_rewritten
Change the default value for the `logging_log_connections` and `logging_log_disconnections` charm config options to `true` and set the right value to the other parameters in the Patroni configuration file template.
There is more info in the Jira ticket.
This is a port of https://github.com/canonical/postgresql-k8s-operator/pull/702.
> [DPE-5512] postgresql.conf hardening

- src/constants.py
Remove tracking of snap channel for the charmed-postgresql snap
> [MISC] Stop tracking channel for held snaps

- lib/charms/data_platform_libs/v0/data_interfaces.py
- src/relations/postgresql_provider.py
- tests/unit/test_postgresql_provider.py
Data Interfaces v40 introduces a blocking mechanism, to avoid write operations on Relation Data before the relation is inialized.
This is important so that `Provider` would never try to add data before `Requirer` clearly indicating if Juju Secrest are to be used or not. (The `Provider` is adding this information within its `relation-created` handler).
NOTE: Any calls on `update_relation_data()` before this stage may appear as plain text. Thus the blocking behavior introduced.
Without fixes on the code, tests publishing `uri` premature may fail.
https://github.com/canonical/postgresql-operator/actions/runs/11002875807/job/30551092035
Note that in real life this is not a valid scenario, since `uris` contain credentials. Now, before credentials are distributed (which happens correctly in the …
> [DPE-5306] Data Interafces v40

- src/prometheus_alert_rules/patroni_rules.yaml
- src/prometheus_alert_rules/pgbouncer_rules.yaml
- src/prometheus_alert_rules/postgresql_rules.yaml
- tox.ini
Alert rule descriptions do not provide much guidance about what actions the user can take.
Improve the descriptions of the COS alert rule expressions where possible.
(Port of [K8s changes](https://github.com/canonical/postgresql-k8s-operator/pull/727))
> [DPE-5658] Update COS alert rules

- src/charm.py
Adds warning and status change before re-initialising to make it more visible in logs
> [DPE-5712] Add warning logs to Patroni reinitialisation

- src/charm.py
- src/relations/postgresql_provider.py
- tests/unit/test_postgresql_provider.py
Early setting of the tls flags can cause errors when setting too early. [E.g.](https://github.com/canonical/pgbouncer-operator/actions/runs/11788944012/job/32837736355)
```
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1952, in <module>
main(PostgresqlOperatorCharm)
File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/__init__.py", line 343, in __call__
return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/_main.py", line 543, in main
manager.run()
File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/_main.py", line 529, in run
self._emit()
File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/_main.py", line 518, in …
```
> [MISC] Merge update_tls_flag into update_endpoints

- src/cluster.py
- src/relations/postgresql_provider.py
- tests/integration/new_relations/test_new_relations.py
- tests/unit/test_cluster.py
- tests/unit/test_postgresql_provider.py
Currently, the charm sets all replica units as readonly endpoints to clients, no matter if the unit is functioning or not.
The PR adds filtering for the read only endpoints based on Patroni's cluster endpoint.
> [DPE-5714] Filter out degraded read only endpoints

- src/backups.py
- tests/unit/test_backups.py
When trying to restore to the latest time from a repository, the charm complains that a backup ID is required.
Allow users to restore without a backup ID (with only the `--restore-to-time=latest` parameter).
Also, add a new check that prevents the PITR and warns the user that there is no base backup in the latest timeline if there isn't one. Previously, if the user tried to restore from that timeline, the restore would be reported as successful, but in fact, it didn't happen.
This is a port of https://github.com/canonical/postgresql-k8s-operator/pull/787.
> [DPE-6062] Allow `--restore-to-time=latest` without a `backup-id`

- src/backups.py
- tests/unit/test_backups.py
This PR removes unnecessary calls to [reload_patroni_configuration](https://github.com/canonical/postgresql-operator/blob/3eb537d9f361fd1fc88b674b89f1b51e5f3df58b/src/cluster.py#L797-L805) method, in cases where the charm's [update_config](https://github.com/canonical/postgresql-operator/blob/3eb537d9f361fd1fc88b674b89f1b51e5f3df58b/src/charm.py#L1683-L1755) method is **explicitly called** right before such line. This method already reloads the Patroni configuration internally ([reference](https://github.com/canonical/postgresql-operator/blob/3eb537d9f361fd1fc88b674b89f1b51e5f3df58b/src/charm.py#L1739)), so it does not make sense to preserve these lines.
---
This discovery was done thanks to the help of @lucasgameiroborges
> [MISC] Clean-up duplicated Patroni config reloads

- config.yaml
- src/config.py
- tests/integration/test_config.py
The `max_locks_per_transaction ` PostgreSQL setting is not available for users to set.
Create a config option to expose it to the users.
Port of https://github.com/canonical/postgresql-k8s-operator/pull/804.
> [DPE-5533] Add `max_locks_per_transaction` config option

- src/prometheus_alert_rules/postgresql_rules.yaml
Typo fixes on 2 alert rules, one of them being the root cause of https://github.com/canonical/postgresql-k8s-operator/issues/800
> [DPE-6171] Fix typos in alert rules

- src/backups.py
- src/charm.py
- src/relations/async_replication.py
- src/relations/db.py
- src/relations/postgresql_provider.py
This PR defines a set of charm properties to reduce the chance of introducing typos when checking for specific keys in the app / unit data-bags, as well as reduce the cognitive load of logical statements.
The **new** properties are:
- `is_cluster_restoring_backup`.
- `is_cluster_restoring_to_time`.
- `is_unit_departing`
- `is_unit_stopped`.
The **existing** properties, now used throughout the codebase are:
- `is_cluster_initialised`.
> [MISC] Define charm utility properties

- tests/integration/new_relations/test_new_relations_2.py
Test consistently fails. Created [DPE-6580](https://warthogs.atlassian.net/browse/DPE-6580) to fix and reenable.
[DPE-6580]: https://warthogs.atlassian.net/browse/DPE-6580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MISC] Disable Nextcloud test

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/constants.py
- tests/integration/helpers.py
- tests/integration/new_relations/test_new_relations_1.py
- tests/integration/new_relations/test_relations_coherence.py
This PR moves certain string into constant values, so that they could be referenced throughout the codebase.
These two in particular (i.e. the `admin` permission group and the `postgres` default database name) will be used in the upcoming LDAP support. These changes are proposed an isolation, as they have nothing to do with the LDAP support itself.
> [MISC] Define charm constants

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/postgresql_provider.py
- tests/unit/test_postgresql_provider.py
This PR contains a slight refactor to make code more compatible with the upcoming LDAP integration.
In that effort, we would need to sanitise the list of `extra-user-roles` a Juju cluster administrator could provide via the data-integrator [charm](https://github.com/canonical/data-integrator), so that none of the upcoming _access groups_ (see [spec](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit?tab=t.0) for context) is provided as a security by-pass. With that in mind, some centralised place to perform this sanitisation is required, and such operation is easier to carry on considering the list of roles as a `list`, instead of a comma-separated `str`.
> [MISC] Sanitize PostgreSQL extra-user-roles arg

- lib/charms/postgresql_k8s/v0/postgresql.py
This PR fixes PR https://github.com/canonical/postgresql-operator/pull/782 by making the PostgreSQL charm lib compatible with Python 3.8 (required by PGBouncer VM).
Apologies for the noise 😞
> [MISC] Fix PostgreSQL lib function signature

- README.md
Security section of the README contains an old link to the LaunchPad.
We are using GitHub Private vulnerability reporting now.
Update the link and wording,
Additionally, minor refactoring for headings syntax.
> Update README file's security section

- concierge.yaml
- tests/integration/test_subordinates.py
* Set series for the Ubuntu advantage charm
* Disable Landscape subordinate test
* Roll back to LTS Lxd
> [MISC] Disable landscape subordinate test lxd

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/db.py
- src/relations/postgresql_provider.py
- src/upgrade.py
- tests/unit/test_db.py
- tests/unit/test_postgresql_provider.py
This is the 1st PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-operator/tree/sinclert/ldap-integration-all).
This PR defines three different _access groups_, in order to differentiate authentication methods within the `pg_hba.conf` file when LDAP is activated (i.e. the GLAuth charm related). These _access groups_ are not yet put into such file, but they are leveraged in order to:
- Assign any charm internal user to the _internal-access_ group.
- Assign any charm relation user to the _relation-access_ group.
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit?tab=t.0).
> [DPE-6345] LDAP I: Create access groups

- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/glauth_k8s/v0/ldap.py
- lib/charms/postgresql_k8s/v0/postgresql_tls.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- src/constants.py
- tests/integration/helpers.py
- tests/integration/test_backups_pitr_aws.py
- tests/integration/test_backups_pitr_gcp.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
This is the 2nd PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-operator/tree/sinclert/ldap-integration-all).
This PR introduces the `ldap` V0 charm library, as well as the `certificate-transfer` V0 charm library. Despite having V1 of the latter already published, V0 requires `jsonschema` instead of `pydantic` which plays nicely with the version of the TLS charm lib we are using (see [code](https://github.com/canonical/postgresql-operator/blob/d35b18dd19fb61b1cea25e37e95ee1f67b388cc6/lib/charms/tls_certificates_interface/v2/tls_certificates.py#L312)). I would say whenever we bump one, we bump the other.
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQ …
> [DPE-6345] LDAP II: Include charm libs

- config.yaml
- src/charm.py
- src/cluster.py
- src/config.py
- src/ldap.py
- templates/patroni.yml.j2
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_ldap.py
This is the 3rd PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-operator/tree/sinclert/ldap-integration-all).
This PR extends the charm configuration to include all the initially proposed configuration options, which are useful for local debugging (some of them will go away before marking the integration complete). In addition, it creates the [PostgreSQLLDAP](https://github.com/canonical/postgresql-operator/blob/ldap-integration/handler-methods/src/ldap.py) class to hold all the GLAuth related handlers, similar to how other classes within the charm hold all the handlers for a particular functionality (i.e. `PostgreSQLBackups`, `PostgreSQLUpgrades`, etc).
- PostgreSQL-LDAP …
> [DPE-6345] LDAP III: Define config and handlers

- src/charm.py
- src/utils.py
- tests/unit/test_charm.py
- tests/unit/test_utils.py
This is the 4th PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-operator/tree/sinclert/ldap-integration-all).
This PR leverages the upcoming `ldap-sync` snap service in order to start the synchronization of LDAP users whenever the PostgreSQL-K8s charm relates to the GLAuth-K8s one.
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit?tab=t.0).
> [DPE-6345] LDAP IV: Define snap service

- config.yaml
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/config.py
- tests/unit/test_charm.py
This is the 5th PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-operator/tree/sinclert/ldap-integration-all).
This PR introduces the last configuration option for the integration: `ldap_map`. This configuration option will be used to specify a mapping between LDAP users coming from specific LDAP groups, to pre-created PostgreSQL authorization groups, so they can actually connect / query the database. The syntax has been copied from Percona's MySQL ([reference](https://docs.percona.com/percona-server/8.0/ldap-simple-variables.html#authentication_ldap_simple_group_role_mapping)).
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit? …
> [DPE-6345] LDAP V: Define mapping option

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- tests/integration/test_plugins.py
* Disable pgaudit during plugin initialisation
* Update charm libraries
Port of https://github.com/canonical/postgresql-k8s-operator/pull/923
> [DPE-6815] disable pgaudit during extensions changes

- concierge.yaml
- tests/integration/ha_tests/test_self_healing.py
Disable network cut tests for arm64
> [MISC] Disable network cut tests on arm

- terraform/main.tf
- terraform/variables.tf
The current terraform configuration does not include the option to expose the postgresql application. Since this module is used by [hockeypuck](https://github.com/canonical/hockeypuck-k8s-operator/blob/73052786638e36ea011e0dcead39ea583ce8558d/terraform/product/main.tf#L27) charm in the staginge environment, this is a requirement for the hockeypuck terraform files to work. The expose directive needs to be enabled to allow cross model relation between postgresql charm and the hockeypuck charm.
Add a variable `enable_expose` that adds `expose {}` only if it is set to `True`.
> Add conditional expose directive

- actions.yaml
Make scope mandatory for promote to primary action
> [MISC] No default scope in promote action

- lib/charms/postgresql_k8s/v0/postgresql.py
This PR is a port of this other PostgreSQL K8s [PR](https://github.com/canonical/postgresql-k8s-operator/pull/957). The bug fix will only be noticeable on **this repository**.
> [MISC] Extend relation-user listing syntax

- tests/integration/ha_tests/test_self_healing_1.py
- tests/integration/ha_tests/test_self_healing_2.py
- tests/integration/ha_tests/test_self_healing_3.py
- tests/spread/test_self_healing_1.py/task.yaml
- tests/spread/test_self_healing_2.py/task.yaml
- tests/spread/test_self_healing_3.py/task.yaml
HA tests take a while to complete.
Split HA tests to speed up execution (through multiple runners).
Will create the same PR for PG 14 (the priority now is PG 16).
> [MISC] Split HA tests

- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/postgresql_k8s/v0/postgresql_tls.py
Syncing postgresql lib changes between 16/edge and main
> [MISC] Sync postgresql lib

- spread.yaml
Currently spread conf expects to be able to ssh into the runner user without a password. New images now have a password set, so it's removed to reenable CI.
> [MISC] Delete runner password

- spread.yaml
Copy of https://github.com/canonical/postgresql-operator/pull/912 for PG 14.
Delete the runner user pass to reenable amd64 ci.
> [MISC] Remove runner password

- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
Warning is annoying
* Switch to the new way of getting the version
* Update libs
> [MISC] Remove JujuVersion warning in 14/edge

- lib/charms/postgresql_k8s/v1/postgresql.py
- src/charm.py
- src/relations/postgresql_provider.py
- tests/unit/test_charm.py
- tests/unit/test_postgresql_provider.py
We missed creating a new folder and file for the v1 postgresql charm lib in the predefined instance level roles PR.
https://github.com/canonical/postgresql-operator/pull/881
Retroactively create new file and folder for the major version bump
> Create new folder for v1 of postgresql charm lib

- tests/integration/ha_tests/test_upgrade.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
The newly merged PR (with snap bump) has passed PR testing[1] but failing on release[2].
The reason here is a test imperfection (we've missed the on-Git case):
- on-PR: we are testing incompatible case (due to +dirty charm.py version)
- on-Git: we are testing compatible case, paused after the first unit upgrade
[1] https://github.com/canonical/postgresql-operator/pull/943
[2] https://github.com/canonical/postgresql-operator/actions/runs/15539934165/job/43748494710
Improve the test to support both cases: on-PR and on-Git for already merged PRs.
> [DPE-7502] Improve upgrade tests to support both (in)compatible scenarios

- docs/explanation/roles.md
- Missing explanation for catalog/database level roles.
- The `charmed_dba` role was marked as still WIP.
- Mark `charmed_dba` role as complete and add additional info to it.
- Add explanation for catalog/database level roles.
> [DPE-7556] Add catalog/database level roles and mark chamed_dba_role as done

- src/charm.py
- tests/unit/test_charm.py
Remove replica reinitialisations to allow them to sync up in case of a large database
> [DPE-7614] Remove replica reinitialisations

- lib/charms/postgresql_k8s/v1/postgresql.py
- templates/patroni.yml.j2
- tests/integration/test_predefined_dba_role.py
Users who are members of the `charmed_dba` role cannot connect to other databases.
Allow members of the `charmed_dba` role to connect to other databases via HBA rules.
> [DPE-7627] Allow `charmed_dba` role members to connect to other databases

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- src/charm.py
- tests/unit/test_charm.py
* Try to re-enable extensions after restore of a backup
* Update libs
> [DPE-7678] Enable disable extensions afrer restore

- docs/explanation/logs.md
- docs/how-to/switchover-failover.md
- docs/reference/troubleshooting/cli-helpers.md
- docs/reference/troubleshooting/index.md
- refresh_versions.toml
- scripts/cluster_topology_observer.py
- src/backups.py
- src/charm.py
- src/cluster.py
- src/relations/async_replication.py
- templates/patroni.yml.j2
- templates/pgbackrest.logrotate.j2
- tests/integration/test_tls.py
- tests/spread/test_upgrade.py/task.yaml
- tests/spread/test_upgrade_from_stable.py/task.yaml
- tests/unit/test_backups.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
The snap user `snap_daemon` has been deprecated by SNAP team,
see: https://forum.snapcraft.io/t/system-usernames/13386
Also the newer charmed-postgresql snap is available with new parts there.
* Bump snap revision to 197/198.
* Use `_daemon_` (UID:584792) instead of `snap_daemon` (UID:584788)
* temporary disable upgrade tests due to snap user change.
Tests will be re-enabled after releasing to edge, as we do not
provide upgrade path for snap ownership changes.
Upgrade path is unnecessary here, as it is a first stable release to PG16 charm.
* Stop creating $SNAP_COMMON/data/db (unnecessary) + polishing
* new snap adds postgresql-16-repack PG extention
> [DPE-7691] Bump snap revision to 197/198 to use _daemon_ (584792)

- tests/spread/test_upgrade_from_stable.py/task.yaml
The upgrade test was temporary disabled in commit 94f31bdec0213655c81fdd379b18a846eacbae2e 
to migrate on new snap user. The migration has been completed.
The new charm has been merged and released, we should re-enable test.
> [DPE-6965] Re-enable charm upgrade tests (new snap _daemon_ user)

- src/charm.py
To support logical replications and keep 9 units installation possible
+ async replication, we should bump slots count.
Bump slots to support all features simultaneously.
> Bump PG slots max_replication_slots / max_wal_senders = 25

- src/charm.py
- src/cluster.py
The charm inits class PostgreSQL on each `self.postgresql.*` call (which we have many).
Visualizing each Patroni API /cluster request:
```
@ src/cluster.py:263 @ class Patroni:
if response := self.parallel_patroni_get_request(
f"/{PATRONI_CLUSTER_STATUS_ENDPOINT}", alternative_endpoints
):
+            logger.debug(f"Patroni cluster members: %s", response["members"])
return response["members"]
raise RetryError(last_attempt=Exception("Unable to reach any units"))
```
Results:
```
> juju deploy ./postgresql_ubuntu@24.04-amd64.charm
> juju debug-log --replay | grep -c "Patroni cluster members"  # default 16/edge r836
113
> juju debug-log --replay | grep -c "Patroni cluster members"  # this PR
22
> juju debug-log --replay | grep -c "Init class PostgreSQL"  # this PR on powerful HW
3
> juju …
```
> Reuse class PostgreSQL on each self.postgresql.* call

- docs/.custom_wordlist.txt
- docs/explanation/roles.md
Not all the predefined roles are documented after the last refactoring in that list.
Add the missing roles and update the SQL queries outputs.
Also, remove the mentions of relation users having the ownership of the objects created within the databases. The ownership of those objects now (in PG 16) belongs to the `charmed_<database-name>_owner` role.
> [DPE-7792] Update predefined roles docs

- docs/how-to/deploy/sunbeam.md
MicroStack docs migration led to some broken links in the Sunbeam guide.
Replaced MicroStack links with their equivalents in the [new OpenStack docs](https://canonical-openstack.readthedocs-hosted.com/en/latest/).
PR on 16: https://github.com/canonical/postgresql-operator/pull/1062
> Fix MicroStack links

- lib/charms/postgresql_k8s/v1/postgresql.py
- src/charm.py
- tests/unit/test_charm.py
Don't skip custom users when generating pg_hba configuration
> [DPE-7594] Add custom users to pg_hba filter

- docs/how-to/deploy/tls-vip-access.md
- docs/reference/releases.md
- docs/reference/versions.md
The end-users have troubles to find the proper/expected SNAP revisions for the specific Charm revision in Git.
List them on release notes.
> Add SNAP revisions to Releases page

- tests/integration/test_backups_ceph.py
- tests/spread/test_backups_ceph.py/task.yaml
The test that checks the backup on microceph runs only for AMD64.
Change the pinned revision to a channel and enable the test for ARM64.
Port of https://github.com/canonical/postgresql-operator/pull/1126.
> [DPE-8063] Enable microceph test for arm64

- tests/integration/test_backups_ceph.py
- tests/spread/test_backups_ceph.py/task.yaml
The test that checks the backup on microceph runs only for AMD64.
Change the pinned revision to a channel and enable the test for ARM64.
> [DPE-8062] Enable microceph test for arm64

- src/charm.py
- tests/unit/test_charm.py
Port of https://github.com/canonical/postgresql-operator/pull/1135 to 14/edge
If the snap fails to install the charm will attempt to block, but subsequent hooks will error out and there should be no way to automatically recover
Don't handle the snap installation error so that the install hook can fail and can be retried with `juju resolve`
> [MISC] Don't block if the snap cannot be installed

- src/constants.py
The charm ships non-latest PostgreSQL 14.18.
Bump PostgreSQL to 14.19.
> DPE-8296 Bump PostgreSQL to 14.19

- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- src/charm.py
- src/relations/tls.py
- tests/integration/helpers.py
- tests/integration/test_backups_ceph.py
* Prevent early generation of the internal certificate
* Use peer address as comon name in peer certificates
> [DPE-8320] Fix backups with internal certificates

- refresh_versions.toml
PostgreSQL cluster is not solid with flickering IO environment.
See https://warthogs.atlassian.net/browse/DPE-8470
Updating snap to deliver the latest Patroni 3.3.8 and enabling strict mode (followup commits).
> DPE-8470 Bump patroni from 3.2.2 to 3.3.8

- src/constants.py
PostgreSQL cluster is not solid with flickering IO environment.
See https://warthogs.atlassian.net/browse/DPE-8470
Updating snap to deliver the latest Patroni 3.3.8 and enabling strict mode (followup commits).
> DPE-8470 Bump snap for Patroni to 3.3.8
