canonical/postgresql-operator

- tox.ini
One of the integration tests isn't passing the caching envvars
> Use caching for charm-integration

- lib/charms/operator_libs_linux/v0/apt.py
- lib/charms/operator_libs_linux/v1/systemd.py
- tests/integration/new_relations/test_new_relations.py
- tests/unit/test_charm.py
- tox.ini
Very limited amount of files were being checked through `codespell`
Expand the amount of files checked by codespell
> Expand the amount of files checked by codespell

- src/cluster.py
- tests/integration/ha_tests/conftest.py
- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_self_healing.py
* Sending SIGINT to postgresql to trigger a restart
* Sending SIGTERM to patroni to trigger a restart
* disabling freeze postgresql process test
> Try SIGINTing for restarts

- src/charm.py
- src/cluster.py
- src/constants.py
- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_self_healing.py
- tests/unit/test_cluster.py
* [DPE-1657](https://warthogs.atlassian.net/browse/DPE-1657)
* Use ppas for patroni, pgbackrest and pgbouncer
Moving the held revision
Use ppas for patroni, pgbackrest and pgbouncer
[DPE-1657]: https://warthogs.atlassian.net/browse/DPE-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Switch to latest SNAP

- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- metadata.yaml
- poetry.lock
- pyproject.toml
- src/charm.py
- src/constants.py
- src/grafana_dashboards/postgresql-metrics.json
- templates/patroni.yml.j2
- tests/integration/test_charm.py
- tests/unit/test_charm.py
COS support for PG [DPE-1776](https://warthogs.atlassian.net/browse/DPE-1776)
Added COS relation using grafana-agent operator.
Follow [o11y team guide](https://discourse.charmhub.io/t/using-the-grafana-agent-machine-charm/8896#step-4-relate-grafana-agent-to-cos-lite-prometheus-loki-and-grafana)
- Fix pinned snap version after snap [PR#9](https://github.com/canonical/charmed-postgresql-snap/pull/9)
[DPE-1776]: https://warthogs.atlassian.net/browse/DPE-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cos integration

- src/constants.py
- tests/integration/test_tls.py
Update rev to add missing plug to snapped psql
> [DPE-2050] Bump snap rev

- src/constants.py
- tests/integration/ha_tests/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/new_relations/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
Security notification:
```
Revision r57 (amd64; channels: 14/edge)
* libperl5.34: 6112-2
* libpython3.10: 6139-1
* perl: 6112-2
* perl-modules-5.34: 6112-2
```
* Bump the OCI to update the packages
> Update revision due to outdated snap pkgs

- lib/charms/operator_libs_linux/v2/snap.py
- src/charm.py
- tests/unit/test_charm.py
Lib feature to create aliases was merged
Switch alias creation to use the lib
> [DPE-2090] aliases with lib

- lib/charms/grafana_agent/v0/cos_agent.py
Pydantic 2 is causing the charm build to [fail](https://github.com/canonical/postgresql-operator/actions/runs/5426600847/jobs/9892167948).
Update the COS library to the version from https://github.com/canonical/grafana-agent-k8s-operator/pull/215 to enable the build again.
> [DPE-2233] Bumped COS lib

- src/relations/db.py
Populate extensions to fix hanging indico consume bug.
> [DPE-2341] Populate extensions in unit databag

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/s3.py
Updating some of the charm libs. S3 update should fix https://github.com/canonical/postgresql-operator/issues/180
> [DPE-2218] Update charm libs to get s3 relation fix

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/upgrade.py
- src/prometheus_alert_rules/postgresql_rules.yaml
No alert rules set when integrating with COS
Add some basic prometheus rules and an empty dir for loki rules
> [DPE-2038] Basic alerts

- lib/charms/data_platform_libs/v0/data_interfaces.py
- src/backups.py
- tests/unit/test_backups.py
Copy fixes for stuck blocking and multiple attempts to create the s3 bucket.
> [MISC] Copy fixes of DPE-2626 and DPE-2627 from k8s

- tests/integration/new_relations/helpers.py
- tests/integration/new_relations/test_new_relations.py
Minimal port of https://github.com/canonical/postgresql-k8s-operator/pull/263
Tweak tests to work with data_interfaces secrets.
> [DPE-2299] Relation secrets

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- pyproject.toml
- tests/integration/test_backups.py
Can't run the backup integration tests without accessing secrets
Skip tests if PR from a forked repo
> [DPE-2804] Conditional backup tests

- src/relations/db.py
- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_replication.py
- tests/integration/ha_tests/test_upgrade.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/helpers.py
- tests/integration/test_db.py
Block the charm if the legacy interface requests roles
> [DPE-3077] Block roles in legacy interface

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/sync_issue_to_jira.yaml
- poetry.lock
- pyproject.toml
- tests/integration/ha_tests/test_replication.py
- tests/integration/ha_tests/test_restore_cluster.py
- tests/integration/ha_tests/test_self_healing.py
- tests/integration/ha_tests/test_upgrade.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/new_relations/test_new_relations.py
- tests/integration/test_backups.py
- tests/integration/test_charm.py
- tests/integration/test_db.py
- tests/integration/test_db_admin.py
- tests/integration/test_password_rotation.py
- tests/integration/test_plugins.py
- tests/integration/test_tls.py
Switching to latest dpw and self hosted runners.
Backup test seem to work fine now.
> [DPE-2904] Switching to self-hosted runners

- tests/integration/new_relations/test_new_relations.py
> [DPE-2904] Missed redundant marks

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- pyproject.toml
- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_restore_cluster.py
- tests/integration/helpers.py
- tests/integration/new_relations/test_new_relations.py
- tests/integration/test_db.py
* Update ruff config
* Drive by tweaks of the integration tests
> [MISC] Integration tests tweaks

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/integration/test_backups.py
- tests/integration/test_subordinates.py
Adding basic tests for landscape-client subordinate.
> [DPE-3644] Landscape client

- .github/workflows/ci.yaml
- tests/integration/test_subordinates.py
Subordinate test deploys ubuntu-advantage charm as well.
> [DPE-3644] Test for Ubuntu Advantage subordinate

- src/relations/db.py
- src/relations/postgresql_provider.py
Should prevent pgb from restarting on each run of update status
> [MISC] Order set of replicas

- src/charm.py
- src/constants.py
- tests/integration/test_charm.py
- tox.ini
> [MISC] Rollback Patroni update

- LICENSE
Substitute template in LICENSE file to accurately reflect Canonical's copyright.
> [DPE-4423] Update LICENSE file with correct copyright info

- LICENSE
This reverts commit 5ef9c536197fa5f99b4cbcca394ccd72708234dd.
> [DPE-4423] Revert "update LICENSE file (#473)"

- config.yaml
- src/config.py
- src/constants.py
- templates/patroni.yml.j2
- tests/integration/test_plugins.py
- tests/unit/test_charm.py
Added `timescaledb` plugin/extension, as described in [issue](https://github.com/canonical/postgresql-operator/issues/469)
> Added `timescaledb` plugin/extension

- tests/integration/new_relations/test_relations_coherence.py
As desribed [here](https://github.com/canonical/postgresql-operator/issues/449), added test for checking relations coherence
> Added test for relations coherence

- README.md
- Updated some out-of-date juju commands (e.g. `run-action`, integration with `tls-certificates-operator`) 
- Polished the structure and content for more clarity
> DPE-4901 Update README.md

- lib/charms/tempo_k8s/v2/tracing.py
- src/charm.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
* Handle model error during _on_start hook
* Remove stale TLS test
> [MISC] Handle on start secret exception and remove stale test

- src/backups.py
Output of command was converting timezones to local time, which can generate confusion + unit test was failing if local timezone not UTC.
Thanks to @dragomirp for raising this issue.
> [MISC] Show start/end time in UTC time in list-backups output

- lib/charms/tempo_k8s/v2/tracing.py
- tests/unit/test_backups.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
* Bump charm libs
* Move more tests to not rely on TestCase
> [MISC] Bump libs and remove TestCase

- src/grafana_dashboards/postgresql-metrics.json
port of https://github.com/canonical/postgresql-k8s-operator/pull/733, exact same approach.
> [DPE-4469] Polish cos dashboard

- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
Update charm libs
Should fix https://github.com/canonical/postgresql-k8s-operator/issues/772 for VM
> [MISC] Bump libs

- .github/workflows/ci.yaml
- lib/charms/postgresql_k8s/v0/postgresql_tls.py
- src/charm.py
- src/relations/db.py
A more general fix to secrets resetting
> [DPE-6320][DPE-6325] General secrets resetting fix

- src/constants.py
Update Snaps to include Postgresql 14.15
> [MISC] Update to 14.15

- .github/workflows/approve_renovate_pr.yaml
- .github/workflows/check_pr.yaml
- .github/workflows/ci.yaml
- .github/workflows/promote.yaml
- .github/workflows/release.yaml
- .github/workflows/sync_docs.yaml
- charmcraft.yaml
- concierge.yaml
- config.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/config.py
- src/relations/postgresql_provider.py
- templates/patroni.yml.j2
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/new_relations/helpers.py
- tests/integration/new_relations/test_new_relations_1.py
- tests/integration/test_backups_aws.py
- tests/integration/test_backups_ceph.py
- tests/integration/test_backups_gcp.py
- tests/integration/test_backups_pitr_aws.py
- tests/integration/test_backups_pitr_gcp.py
- tests/integration/test_config.py
- tests/integration/test_tls.py
- tests/unit/test_postgresql_provider.py
* Merge main
* Enable cached build
* Use latest/stable lxd
> [DPE-6112] Sync main

- src/constants.py
This PR updates PostgreSQL snaps to the latest revisions.
> [MISC] Update snapped PostgreSQL

- tests/integration/ha_tests/test_self_healing.py
Disable network cut tests for arm64
> [MISC] Disable network cut tests on arm

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
* Disable pgaudit during plugin initialisation
* Update charm libraries
Port of https://github.com/canonical/postgresql-operator/pull/840 and https://github.com/canonical/postgresql-k8s-operator/pull/923
> [DPE-6815] disable pgaudit during extensions changes

- actions.yaml
Make scope mandatory for promote to primary action
> [MISC] No default scope for promote action

- docs/explanation/index.md
There was a missing link to roles.md
Add link to roles.md
> Update index.md: add link to roles.md

- refresh_versions.toml
> [DPE-7502] Update PG to 16.9

- src/constants.py
> [DPE-7502] Update PG to 14.18

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/relations/postgresql_provider.py
- tests/integration/ha_tests/test_async_replication.py
- tests/integration/helpers.py
- tests/unit/test_postgresql_provider.py
Backport of https://github.com/canonical/postgresql-operator/pull/959 to 14/edge:
Tweaks syncing of pg_hba trigger changes
> [MISC] Backport #959 to 14/edge

- .github/renovate.json5
Looks like the team got renamed
> [MISC] Renovate team

- poetry.lock
- pyproject.toml
- tests/integration/spaces/test_spaced_database.py
- tests/spread/test_upgrade.py/task.yaml
* Use beta branch for spaces tests (regression caused by https://github.com/canonical/postgresql-test-app/pull/368)
* Re-enable upgrade from edge test
> [MISC] Use test app beta for isolated test

- docs/explanation/architecture.md
- docs/how-to/switchover-failover.md
- docs/reference/troubleshooting/cli-helpers.md
Docs update for https://github.com/canonical/postgresql-operator/pull/1027
> [DPE-7685] Docs PR for setpriv shim

- refresh_versions.toml
- tests/integration/ha_tests/test_upgrade.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/new_relations/test_new_relations_1.py
- tests/integration/new_relations/test_relations_coherence.py
* Snap update (Remove psql setpriv shim)
* Switch stable upgrade test to track 16/stable
* Switch data integrator to use noble series
> [MISC] Remove psql setpriv shim and switch stable upgrade tests to 16/stable

- poetry.lock
- pyproject.toml
Includes fix in https://github.com/canonical/charm-refresh/pull/19
> Update charm-refresh to v3.1.0.2

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
> [MISC] Update charm libs

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- src/cluster.py
- tests/integration/ha_tests/test_scaling.py
- tests/integration/ha_tests/test_scaling_three_units.py
- tests/integration/ha_tests/test_scaling_three_units_async.py
- tests/integration/ha_tests/test_self_healing_1.py
- tests/integration/ha_tests/test_self_healing_2.py
- tests/integration/ha_tests/test_self_healing_3.py
- tests/unit/test_cluster.py
Port of https://github.com/canonical/postgresql-operator/pull/1196 for 16/edge
* Set strict sync mode in patroni when multiple sync units are requested
> [MISC] Strict sync mode
